# grade_report.R — Appendix 用 GRADE レポート生成
#
# grade_report():
#   複数の pmatools オブジェクトから、Appendix にそのまま使えるレポートを生成する。
#   含まれる内容:
#     1. Summary of Findings テーブル（grade_table）
#     2. 各ドメインの判断根拠（ドメイン別詳細テキスト）
#   出力形式: "docx" / "html" / "pdf" / "md"
#
# 依存: officer (docx), rmarkdown (html/pdf/md), flextable

#' Generate a GRADE appendix report
#'
#' @param outcomes A named list of \code{pmatools} objects.
#' @param primary Character vector of primary outcome names (passed to \code{grade_table}).
#' @param palette Colour palette: \code{"pastel"} (default) or \code{"classic"}.
#' @param format Output format(s): one or more of \code{"docx"}, \code{"html"},
#'   \code{"pdf"}, \code{"md"}. Default \code{"docx"}.
#' @param output_dir Directory for output files. Default \code{getwd()}.
#' @param output_file Base filename without extension. Default \code{"grade_report"}.
#' @param title Report title. Default \code{"GRADE Certainty of Evidence Assessment"}.
#' @param show_domains Logical. Show per-domain columns in the SoF table (default TRUE).
#'
#' @return Invisibly returns a character vector of output file paths.
#'
#' @examples
#' \dontrun{
#' grade_report(
#'   outcomes = list("Depression response" = g1, "Insomnia remission" = g2),
#'   primary  = "Depression response",
#'   format   = c("docx", "html"),
#'   output_dir = "outputs/"
#' )
#' }
#'
#' @export
grade_report <- function(outcomes,
                         primary      = NULL,
                         palette      = c("pastel", "classic"),
                         format       = "docx",
                         output_dir   = getwd(),
                         output_file  = "grade_report",
                         title        = "GRADE Certainty of Evidence Assessment",
                         show_domains = TRUE,
                         per          = 1000,
                         prediction   = FALSE) {

  if (!is.list(outcomes) || !all(vapply(outcomes, inherits, logical(1), "pmatools"))) {
    rlang::abort("outcomes must be a named list of pmatools objects.")
  }
  palette <- match.arg(palette)
  format  <- match.arg(format, choices = c("docx", "html", "pdf", "md"),
                       several.ok = TRUE)

  dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
  out_paths <- character(0)

  md_content <- .build_report_md(outcomes, primary, title, show_domains, per, prediction)

  for (fmt in format) {
    base_path <- file.path(output_dir, paste0(output_file, ".", fmt))

    if (fmt == "md") {
      writeLines(md_content, con = base_path)
      out_paths <- c(out_paths, base_path)
      message("Written: ", base_path)

    } else if (fmt %in% c("html", "pdf")) {
      .check_pkg("rmarkdown")
      tmp_rmd <- tempfile(fileext = ".Rmd")
      writeLines(c(
        "---",
        paste0('title: "', title, '"'),
        paste0('output: ', if (fmt == "html") 'html_document' else 'pdf_document'),
        "---",
        "",
        md_content
      ), con = tmp_rmd)
      rmarkdown::render(
        input       = tmp_rmd,
        output_file = base_path,
        quiet       = TRUE
      )
      out_paths <- c(out_paths, base_path)
      message("Written: ", base_path)

    } else if (fmt == "docx") {
      .check_pkg("officer")
      .check_pkg("flextable")
      out_paths <- c(out_paths,
        .write_docx(outcomes, primary, palette, title, show_domains,
                    per, prediction, base_path))
      message("Written: ", base_path)
    }
  }

  invisible(out_paths)
}

# --------------------------------------------------------------------------
# Markdown report builder
# --------------------------------------------------------------------------
.build_report_md <- function(outcomes, primary, title, show_domains,
                              per = 1000, prediction = FALSE) {
  nms <- names(outcomes)
  if (is.null(nms)) nms <- vapply(outcomes, function(g) g$outcome_name, character(1))

  prim_nms <- if (!is.null(primary)) nms[nms %in% primary]  else character(0)
  sec_nms  <- if (!is.null(primary)) nms[!nms %in% primary] else character(0)

  prim_lbl <- if (length(prim_nms) == 1L) "**Primary outcome**" else "**Primary outcomes**"
  sec_lbl  <- if (length(sec_nms)  == 1L) "**Secondary outcome**" else "**Secondary outcomes**"

  lines <- c(
    paste0("# ", title),
    "",
    paste0("> Generated by `pmatools` package. ",
           "Reference: BMJ 2025 Core GRADE series (Guyatt et al.)."),
    "",
    "## Summary of Findings",
    "",
    "*See Word/HTML output for the full colour-coded flextable.*",
    "",
    .md_sof_table(outcomes, primary, nms, prim_lbl, sec_lbl, per, prediction),
    "",
    "## Domain-by-Domain Rationale",
    ""
  )

  for (i in seq_along(outcomes)) {
    nm <- nms[i]
    g  <- outcomes[[i]]
    group_tag <- if (!is.null(primary)) {
      if (nm %in% primary) " *(Primary)*" else " *(Secondary)*"
    } else ""

    lines <- c(
      lines,
      paste0("### ", nm, group_tag),
      "",
      sprintf(
        "**Final certainty: %s %s** (starting: %s, study design: %s)",
        g$certainty, CERTAINTY_SYMBOLS[[g$certainty]],
        g$starting_quality, g$study_design
      ),
      "",
      "| Domain | Judgment | Downgrade | Source | Notes |",
      "|--------|----------|-----------|--------|-------|"
    )

    d <- g$domain_assessments
    for (j in seq_len(nrow(d))) {
      row <- d[j, ]
      dg  <- if (row$downgrade < 0) as.character(row$downgrade) else "0"
      src <- if (row$auto) "auto" else "manual"
      note_clean <- gsub("\\|", "\\\\|", if (is.na(row$notes)) "" else row$notes)
      lines <- c(lines,
        sprintf("| %s | %s | %s | %s | %s |",
                row$domain, row$judgment, dg, src, note_clean))
    }
    lines <- c(lines, "")
  }

  lines <- c(lines,
    "---",
    "",
    paste0("*Report generated: ", format(Sys.time(), "%Y-%m-%d %H:%M"), "*")
  )

  paste(lines, collapse = "\n")
}

# --------------------------------------------------------------------------
# Plain-text SoF table for Markdown
# --------------------------------------------------------------------------
.md_sof_table <- function(outcomes, primary, nms, prim_lbl, sec_lbl,
                           per = 1000, prediction = FALSE) {
  per_str <- format(per, big.mark = ",", scientific = FALSE)
  hdr <- paste0("| Outcome | k | N | Control rate (per ", per_str,
                ") | Exp. rate (per ", per_str, ") | Effect (95% CI) | Certainty |")
  sep <- "|---|---|---|---|---|---|---|"

  rows <- c()
  for (i in seq_along(outcomes)) {
    nm <- nms[i]
    g  <- outcomes[[i]]
    k  <- g$meta$k
    n  <- .total_n(g$meta)
    cer  <- gsub("\n", " ", .format_cer(g$baseline_risk, per))
    ier  <- gsub("\n", " ", .format_ier(g$meta, g$baseline_risk, per))
    eff  <- gsub("\n", " ", .format_effect(g$meta, g$outcome_type, prediction))
    cert <- paste0(g$certainty, " ", CERTAINTY_SYMBOLS[[g$certainty]])

    if (!is.null(primary)) {
      if (i == 1L || (nm %in% primary) != (nms[i - 1L] %in% primary)) {
        label <- if (nm %in% primary) prim_lbl else sec_lbl
        rows  <- c(rows, paste0("| ", label, " | | | | | | |"))
      }
    }

    rows <- c(rows, sprintf("| %s | %d | %s | %s | %s | %s | %s |",
      nm, k,
      if (is.na(n)) "NR" else format(n, big.mark = ","),
      cer, ier, eff, cert))
  }

  c(hdr, sep, rows)
}

# --------------------------------------------------------------------------
# Word (docx) output using officer + flextable
# --------------------------------------------------------------------------
.write_docx <- function(outcomes, primary, palette, title, show_domains,
                         per, prediction, path) {
  doc <- officer::read_docx()

  doc <- officer::body_add_par(doc, title, style = "heading 1")
  doc <- officer::body_add_par(doc, paste0(
    "Reference: BMJ 2025 Core GRADE series (Guyatt et al.). ",
    "Generated: ", format(Sys.time(), "%Y-%m-%d %H:%M")
  ), style = "Normal")
  doc <- officer::body_add_par(doc, "", style = "Normal")

  doc <- officer::body_add_par(doc, "Summary of Findings", style = "heading 2")

  ft <- grade_table(outcomes, primary = primary, palette = palette,
                    show_domains = show_domains, per = per, prediction = prediction)
  doc <- flextable::body_add_flextable(doc, ft)
  doc <- officer::body_add_par(doc, "", style = "Normal")

  doc <- officer::body_add_par(doc, "Domain-by-Domain Rationale", style = "heading 2")

  nms <- names(outcomes)
  if (is.null(nms)) nms <- vapply(outcomes, function(g) g$outcome_name, character(1))

  for (i in seq_along(outcomes)) {
    nm <- nms[i]
    g  <- outcomes[[i]]
    group_tag <- if (!is.null(primary)) {
      if (nm %in% primary) " (Primary)" else " (Secondary)"
    } else ""

    doc <- officer::body_add_par(doc, paste0(nm, group_tag), style = "heading 3")
    doc <- officer::body_add_par(doc, sprintf(
      "Final certainty: %s %s  |  Starting: %s  |  Design: %s",
      g$certainty, CERTAINTY_SYMBOLS[[g$certainty]],
      g$starting_quality, g$study_design
    ), style = "Normal")

    d <- g$domain_assessments
    detail_df <- data.frame(
      Domain    = d$domain,
      Judgment  = d$judgment,
      Downgrade = as.character(d$downgrade),
      Source    = ifelse(d$auto, "auto", "manual"),
      Notes     = ifelse(is.na(d$notes), "", d$notes),
      stringsAsFactors = FALSE
    )
    ft_detail <- flextable::flextable(detail_df)
    ft_detail <- flextable::theme_vanilla(ft_detail)
    ft_detail <- flextable::fontsize(ft_detail, size = 9, part = "all")
    ft_detail <- flextable::width(ft_detail, j = 1, width = 1.2)
    ft_detail <- flextable::width(ft_detail, j = 2, width = 1.0)
    ft_detail <- flextable::width(ft_detail, j = 3, width = 0.8)
    ft_detail <- flextable::width(ft_detail, j = 4, width = 0.7)
    ft_detail <- flextable::width(ft_detail, j = 5, width = 3.3)
    ft_detail <- flextable::bg(ft_detail,   bg = "#F0F0F0", part = "header")
    ft_detail <- flextable::bold(ft_detail, part = "header")
    doc <- flextable::body_add_flextable(doc, ft_detail)
    doc <- officer::body_add_par(doc, "", style = "Normal")
  }

  print(doc, target = path)
  path
}

# --------------------------------------------------------------------------
# Package check helper
# --------------------------------------------------------------------------
.check_pkg <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    rlang::abort(sprintf(
      "Package '%s' is required for this output format. Install with: install.packages('%s')",
      pkg, pkg
    ))
  }
}
