# ui_helpers.R - shadcn-style component helpers (HTML wrappers)

`%||%` <- function(a, b) if (is.null(a)) b else a

# Card with optional title and subtitle
pma_card <- function(..., title = NULL, subtitle = NULL, id = NULL) {
  htmltools::div(
    class = "pma-card", id = id,
    if (!is.null(title)) htmltools::div(class = "pma-card-header", title) else NULL,
    if (!is.null(subtitle)) htmltools::div(class = "pma-card-subtitle", subtitle) else NULL,
    ...
  )
}

# Step header with title + "What this step does"
pma_step_header <- function(title, what, why = NULL) {
  htmltools::div(
    class = "pma-step-header",
    htmltools::h2(title, style = "margin-top: 0;"),
    htmltools::p(class = "pma-card-subtitle", what),
    if (!is.null(why)) htmltools::p(class = "pma-why", why) else NULL
  )
}

# Inline tooltip help (?) icon
pma_help <- function(text) {
  htmltools::tags$span(
    class = "pma-help",
    title = text,
    `data-bs-toggle` = "tooltip",
    `data-bs-placement` = "top",
    "(?)"
  )
}

# Stepper (4 steps) - each step is a clickable actionLink
pma_stepper <- function(current_step) {
  steps <- c("Data", "Meta-analysis", "Certainty", "Export")
  htmltools::div(
    class = "pma-stepper",
    lapply(seq_along(steps), function(i) {
      cls <- if (i == current_step) "pma-step current"
             else if (i < current_step) "pma-step done"
             else "pma-step"
      htmltools::tagList(
        shiny::actionLink(
          inputId = paste0("step_jump_", i),
          label   = htmltools::tagList(
            htmltools::span(class = "num", i),
            htmltools::span(steps[i])
          ),
          class = cls,
          style = "text-decoration: none; cursor: pointer;"
        ),
        if (i < length(steps)) htmltools::span(class = "sep", " > ") else NULL
      )
    })
  )
}

# ----- Vendored pmatools version ------------------------------------------
# The app sources pmatools out of R/_pmatools/ instead of installing it, so
# utils::packageVersion("pmatools") errors in the deployed app. app.R reads
# R/_pmatools/VERSION (generated by update_vendor.R) into
# options(pmatools.version_stamp = ...); this is the single place that turns
# the installed-or-vendored question into a display string. Never returns a
# hardcoded number: an unset option means the stamp is genuinely unknown.
pma_pmatools_version <- function() {
  installed <- tryCatch(as.character(utils::packageVersion("pmatools")),
                        error = function(e) NULL)
  if (!is.null(installed)) return(installed)
  stamp <- getOption("pmatools.version_stamp")
  if (is.character(stamp) && length(stamp) == 1L &&
      !is.na(stamp) && nzchar(trimws(stamp))) {
    return(sprintf("%s (vendored)", trimws(stamp)))
  }
  "(vendored; version unknown)"
}

# ----- W4-A output gate: shared confirmation-domain labels -----
# Named after the keys of the state$domain_confirmed logical vector set in
# step3_server(); used by both Step 3 (banner/badge) and Step 4 (export gate).
PMA_DOMAIN_LABELS <- c(
  threshold     = "Configuration",
  rob           = "Risk of Bias",
  inconsistency = "Inconsistency",
  indirectness  = "Indirectness",
  imprecision   = "Imprecision",
  pubias        = "Publication bias"
)

# Human-readable labels of the domains not yet confirmed. `conf` is the
# named logical vector from state$domain_confirmed (NULL = nothing
# confirmed yet, e.g. before Step 3 was opened).
pma_unconfirmed_domains <- function(conf) {
  keys <- names(PMA_DOMAIN_LABELS)
  if (is.null(conf)) return(unname(PMA_DOMAIN_LABELS))
  ok <- vapply(keys, function(k) {
    k %in% names(conf) && isTRUE(conf[[k]])
  }, logical(1))
  unname(PMA_DOMAIN_LABELS[keys[!ok]])
}

# ----- Saved outcomes (multi-outcome Summary of Findings) -----------------
# state$outcomes is a NAMED LIST of pmatools objects (the value of
# state$grade at the moment the user pressed "Save"), keyed by outcome
# label, in insertion order. It is exactly the shape grade_table() expects,
# so it can be passed straight through without reshaping. The save time is
# carried as attr(<obj>, "pma_saved_at") because attributes survive both the
# list round-trip and grade_table()'s inherits() check.

# ----- Dataset provenance guard -------------------------------------------
# A saved outcome carries the signature of the dataset it was rated on, so
# Step 3 / Step 4 can flag outcomes that came from a DIFFERENT dataset than
# the one currently loaded. Mixing outcomes from different datasets into one
# Summary of Findings table is a serious scientific error, but saved work is
# never silently discarded: the app warns, the user decides.
PMA_DATASET_SIGNATURE_ATTR <- "pma_dataset_signature"

# Columns that describe the app's own per-study JUDGMENTS rather than the
# dataset. Step 3 writes RoB / Indirectness edits back into state$data, so
# including them would flag outcomes saved earlier from the very same data.
PMA_SIGNATURE_IGNORE_COLS <- c("rob", "indirectness")

# Stable signature of a long-format dataset. Pure function, no {digest}
# dependency: sorted structural features plus a coarse numeric fingerprint,
# pasted together. Same data -> same string (row order and column order do
# not matter); different studies, rows, columns or numbers -> different
# string. Returns NA_character_ when there is no usable data frame, which
# callers treat as "unknown" (never stale).
pma_dataset_signature <- function(d) {
  if (is.null(d) || !is.data.frame(d) || nrow(d) == 0L || ncol(d) == 0L) {
    return(NA_character_)
  }
  keep <- !(names(d) %in% PMA_SIGNATURE_IGNORE_COLS)
  d <- d[, keep, drop = FALSE]
  if (ncol(d) == 0L) return(NA_character_)
  parts <- c(
    paste0("nrow=", nrow(d)),
    paste0("cols=", paste(sort(names(d)), collapse = "|"))
  )
  if ("studlab" %in% names(d)) {
    studies <- sort(unique(as.character(d$studlab)))
    parts <- c(parts,
               paste0("k=", length(studies)),
               paste0("studies=", paste(studies, collapse = "|")))
  }
  if ("outcome" %in% names(d)) {
    parts <- c(parts, paste0("outcomes=", paste(
      sort(unique(as.character(d$outcome))), collapse = "|")))
  }
  # Numeric fingerprint: per-column (sum, NA count). Order-independent, so
  # re-sorting rows is not mistaken for a new dataset, while different
  # effect data on the same studies still is.
  num_cols <- sort(names(d)[vapply(d, is.numeric, logical(1))])
  if (length(num_cols)) {
    fp <- vapply(num_cols, function(cn) {
      x <- as.numeric(d[[cn]])
      sprintf("%s:%s:%d", cn,
              format(round(sum(x, na.rm = TRUE), 6),
                     scientific = FALSE, trim = TRUE),
              sum(is.na(x)))
    }, character(1))
    parts <- c(parts, paste0("num=", paste(fp, collapse = "|")))
  }
  paste(parts, collapse = "\r")
}

# Signature recorded on one saved outcome (NA when it carries none).
pma_outcome_signature <- function(g) {
  sig <- attr(g, PMA_DATASET_SIGNATURE_ATTR, exact = TRUE)
  if (is.null(sig) || length(sig) != 1) return(NA_character_)
  as.character(sig)
}

# Which saved outcomes came from a different dataset than `signature`?
# Returns a named logical vector aligned with pma_outcomes_list(outcomes).
# Unknown signatures (either side) are NOT flagged: the guard only fires on
# positive evidence of a mismatch.
pma_outcomes_stale <- function(outcomes, signature = NULL) {
  outcomes <- pma_outcomes_list(outcomes)
  out <- rep(FALSE, length(outcomes))
  names(out) <- names(outcomes)
  if (length(outcomes) == 0) return(out)
  if (is.null(signature) || length(signature) != 1 || is.na(signature)) {
    return(out)
  }
  for (i in seq_along(outcomes)) {
    sig <- pma_outcome_signature(outcomes[[i]])
    out[i] <- !is.na(sig) && !identical(sig, as.character(signature))
  }
  out
}

# ----- Outcome provenance guard -------------------------------------------
# pma_dataset_signature() above answers "was this rated on other DATA?". It
# cannot answer "was this rated on another OUTCOME?", because every outcome of
# a review lives in one dataset, so switching between them leaves that
# signature untouched. The Step 3 confirmations depend on the second question,
# and it gets its own signature here.
#
# What counts as a different outcome
# ----------------------------------
# NOT the outcome name. A reviewer who corrects a typo in "Depresion
# response", or relabels a row for the Summary of Findings table, has not
# changed a single judgment, and voiding a finished assessment over a rename
# would punish good bookkeeping. What the Step 3 answers are ABOUT is the body
# of evidence handed to run_ma(), so the identity is built from that - which
# studies, and the arm-level numbers of each - together with the Step 2
# direction answer, because the direction decides which side of the threshold
# counts as benefit and so flips Risk of Bias, Inconsistency and Imprecision
# without changing a number.
#
# Deliberate consequences:
#   * remapping the events (or mean / SD) column - a different outcome
#     measured on the same studies - changes the arm-level numbers, so the
#     identity changes and Step 3 is voided;
#   * flipping the direction voids Step 3, for the reason above;
#   * loading different data voids Step 3 (and the dataset guard fires too);
#   * renaming the outcome, editing its follow-up or unit, or re-running with
#     a different pooling method, tau-squared estimator or summary measure
#     leaves the identity alone. Those change the estimate, not the question:
#     the five domains are recomputed from the new fit anyway, and a change of
#     scale already re-seeds the threshold on its own (threshold_seed_key in
#     step3_grade.R).
#
# Returns NA_character_ when there is no analysis, which callers read as
# "unknown" and never treat as a change.
pma_analysis_signature <- function(ma, small_values = NULL) {
  if (is.null(ma) || !inherits(ma, "meta")) return(NA_character_)
  studlab <- as.character(ma$studlab %||% character(0))
  if (length(studlab) == 0L) return(NA_character_)
  # Sorted, so re-running after a row re-sort is not mistaken for a new
  # outcome; the arm-level vectors follow the same order.
  ord <- order(studlab)
  .field <- function(nm) {
    v <- ma[[nm]]
    if (is.null(v) || length(v) != length(studlab)) return(paste0(nm, "="))
    paste0(nm, "=", paste(format(v[ord], scientific = FALSE, trim = TRUE),
                          collapse = ","))
  }
  paste(
    paste0("studies=", paste(studlab[ord], collapse = "|")),
    .field("event.e"), .field("n.e"), .field("event.c"), .field("n.c"),
    .field("mean.e"), .field("sd.e"), .field("mean.c"), .field("sd.c"),
    paste0("direction=",
           if (is.null(small_values) || length(small_values) != 1L) ""
           else as.character(small_values)),
    sep = "\r"
  )
}

# ----- Inputs that belong to ONE outcome ----------------------------------
# THE single registry of Step 2 / Step 3 input ids whose answers describe the
# outcome currently being rated, rather than the studies, the dataset or how a
# plot is drawn. Two things read it, and nothing else in the app enumerates
# these ids:
#
#   1. the freshness guard in step3_server(). Shiny keeps the last value of an
#      input whose widget has been torn down, so between "the outcome changed"
#      and "Step 3 was rendered again" every one of these still reports the
#      PREVIOUS outcome's answer. The guard records which outcome each id was
#      last touched for, and domain_confirmed() ignores the ones that are out
#      of date;
#   2. pma_clear_outcome_confirmations(), which unticks the confirmation boxes
#      on screen the moment the outcome changes.
#
# ADDING A NEW DOMAIN INPUT? Put its id in the group below that names its tab.
# An id that is missing here is an id whose stale answer can still count
# towards the export gate.
#
# What is deliberately NOT here: the column mapping and model settings (they
# usually carry over to the next outcome unchanged), the per-study risk-of-bias
# and indirectness tables (properties of the studies, not of the outcome), and
# every forest / funnel display field (presentation, re-derived per plot).
PMA_OUTCOME_INPUT_IDS <- list(
  # Step 2 - outcome identity
  identity = c("outcome_name", "small_values", "outcome_follow_up",
               "outcome_unit"),
  # Step 3 - Configuration tab (threshold, control-group risk, responder
  # conversion). Only some of these exist at a time: the binary and continuous
  # branches of output$threshold_panel build different widgets.
  configuration = c("threshold_mode", "threshold_abs", "threshold_ratio",
                    "threshold_cont", "threshold_baseline_input",
                    "threshold_baseline_rationale", "convert_smd_to_or",
                    "baseline_risk_chinn", "responder_p0_rationale",
                    "responder_p0_confirm", "threshold_label",
                    "threshold_confirm"),
  # Step 3 - Risk of Bias. rob_some_concerns / rob_inf_threshold are review-
  # wide conventions with defaults, not per-outcome answers, so they stay.
  rob = c("rob_override", "rob_override_rationale", "rob_confirm_na"),
  # Step 3 - Inconsistency
  inconsistency = c("ci_diff", "threshold_side", "subgroup_explained",
                    "incon_override", "incon_override_rationale",
                    "incon_confirm_na"),
  # Step 3 - Indirectness (the four Core GRADE 5 PICO questions, plus the
  # optional override of their worst-case fold)
  indirectness = c("indir_population", "indir_intervention", "indir_comparator",
                   "indir_outcome", "indirectness", "indir_rationale",
                   "indir_confirm_na"),
  # Step 3 - Imprecision
  imprecision = c("ois_rrr", "ois_sd", "ois_events_override",
                  "ois_n_override", "impre_override",
                  "impre_override_rationale", "impre_confirm_na"),
  # Step 3 - Publication bias
  pubias = c("pubias_registry_complete", "pubias_small_industry",
             "pubias_unpublished", "pubias_funnel_asymmetry",
             "pubias_fa_rationale", "pubias_override",
             "pubias_override_rationale", "pubias_confirm_na"),
  # Step 3 - Final certainty ("Other considerations")
  final = c("other_text", "other_downgrade")
)

pma_outcome_input_ids <- function() {
  unname(unlist(PMA_OUTCOME_INPUT_IDS, use.names = FALSE))
}

# The subset whose cleared value is unambiguous: a confirmation is either
# given or it is not, so these can be pushed to the client without restating
# any widget's declared default. Everything else in the registry clears itself
# when app.R rebuilds the step body from step3_ui() - a freshly built widget
# pushes its own default back to the server, so no default is written twice.
PMA_OUTCOME_CONFIRM_IDS <- c("threshold_confirm", "responder_p0_confirm",
                             "rob_confirm_na", "incon_confirm_na",
                             "indir_confirm_na", "impre_confirm_na",
                             "pubias_confirm_na")

pma_clear_outcome_confirmations <- function(session) {
  for (id in PMA_OUTCOME_CONFIRM_IDS) {
    shiny::updateCheckboxInput(session, id, value = FALSE)
  }
  invisible(NULL)
}

# ----- grade_meta() argument specs for the exported analysis.R ------------
# export_bundle() renders analysis.R from `grade_args`: a named list of
# {value, origin, col} specs, one per grade_meta() argument. An argument it is
# not given falls back to a template default, which is usually the literal
# NULL - so an argument the app supplied but did not declare here disappears
# from the "reproducible" script, and the script reproduces a different rating
# from the one it ships with.
#
# `origin` must be one of "null" / "column" / "scalar" / "vector"; anything
# else aborts (pmatools 0.5.0 breaking change - it used to render NULL in
# silence, which is exactly the failure this list exists to prevent).
PMA_GRADE_ARGS_ATTR <- "pma_grade_args"

pma_arg_spec <- function(value) {
  if (is.null(value) || length(value) == 0L) {
    return(list(value = NULL, origin = "null"))
  }
  # indirectness_subdomains is a data frame; export_bundle() literalises it
  # from the frame itself (.indirectness_subdomains_lit) and never consults
  # the origin, so any valid origin will do.
  if (is.data.frame(value) || is.list(value)) {
    return(list(value = value, origin = "scalar"))
  }
  if (length(value) == 1L) {
    # NA is "not supplied", not the string "NA": rendering shQuote(NA) would
    # put 'NA' into the script and change the call.
    if (is.na(value)) return(list(value = NULL, origin = "null"))
    return(list(value = value, origin = "scalar"))
  }
  list(value = value, origin = "vector")
}

# grade_meta() arguments the app supplies that the bundled analysis.R would
# otherwise drop. Excluded on purpose because export_bundle() already recovers
# them from the rated object: study_design, outcome_type, outcome_name, and
# (whenever a subdomain table exists) indirectness / indirectness_rationale.
#
# threshold_baseline belongs here as of pmatools 0.5.1: the app converts an
# absolute threshold to the analysis scale at a baseline risk it chooses (a
# pooled metaprop estimate, or a manual override with a written rationale),
# and the template now has a slot for it. Without the argument the regenerated
# call re-derives the baseline from the pooled control-arm risk, which is not
# in general the number the reviewer set.
PMA_GRADE_ARGS_EXPORTED <- c(
  "rob", "rob_rationale", "rob_some_concerns", "rob_inflation_threshold",
  "small_values",
  "indirectness", "indirectness_rationale", "indirectness_subdomains",
  "inconsistency", "inconsistency_rationale", "inconsistency_ci_diff",
  "inconsistency_threshold_side", "inconsistency_subgroup_explained",
  "imprecision", "imprecision_rationale",
  "threshold", "threshold_scale", "threshold_baseline",
  "ois_p0", "ois_rrr", "ois_sd", "ois_events", "ois_n",
  "pubias_small_industry", "pubias_funnel_asymmetry", "pubias_rationale",
  "pubias_unpublished", "pubias_registry_complete"
)

# Only the arguments the app actually set are emitted. Before pmatools 0.5.1
# every name above had to be emitted unconditionally, with a "null" spec
# standing in for the ones the app never passed: export_bundle() looked the
# specs up with `grade_args$<name>`, and `$` partial-matches on lists, so with
# `inconsistency` absent `grade_args$inconsistency` returned the
# `inconsistency_ci_diff` spec and wrote that answer into the wrong argument.
# A complete list was the workaround. export_bundle() now looks every name up
# exactly and rejects one it does not know, so a partial list is safe again -
# and a typo here fails loudly instead of vanishing from the script.
pma_grade_arg_specs <- function(args) {
  out <- list()
  for (nm in intersect(PMA_GRADE_ARGS_EXPORTED, names(args))) {
    out[[nm]] <- pma_arg_spec(args[[nm]])
  }
  out
}

# Alert colours follow the existing warning treatment in Step 3
# (output$cert_incomplete_banner): amber #fef3c7 / #b45309, reserved for
# genuine alerts.
PMA_ALERT_BG <- "#fef3c7"
PMA_ALERT_FG <- "#b45309"

# Small "different dataset" badge shown on a stale saved-outcome row.
pma_stale_badge <- function(text = "different dataset") {
  htmltools::span(
    class = "pma-badge",
    style = sprintf(
      "background: %s; color: %s; border: 1px solid %s; white-space: nowrap;",
      PMA_ALERT_BG, PMA_ALERT_FG, PMA_ALERT_FG),
    text
  )
}

# Warning banner above the combined SoF preview. Returns NULL when nothing
# is stale, so callers can drop it straight into a tagList.
pma_stale_warning_banner <- function(n_stale) {
  if (is.null(n_stale) || is.na(n_stale) || n_stale < 1) return(NULL)
  htmltools::div(
    style = paste0(
      "padding: 0.75rem 1rem; margin-bottom: 1rem; ",
      "background: ", PMA_ALERT_BG, "; border-left: 4px solid ", PMA_ALERT_FG,
      "; border-radius: 4px; font-size: 0.9rem;"),
    htmltools::strong("Different dataset detected. "),
    sprintf(paste0(
      "%d of the saved outcomes below %s saved from a dataset other than the ",
      "one currently loaded in Step 1 (marked \"different dataset\"). A ",
      "Summary of Findings table must describe one body of evidence: check ",
      "these rows before combining or exporting them. "),
      n_stale, if (n_stale == 1) "was" else "were"),
    "Nothing has been removed - remove the rows that do not belong, or ",
    "reload the dataset they came from."
  )
}

# Normalizes whatever is in state$outcomes into a valid named list.
pma_outcomes_list <- function(outcomes) {
  if (is.null(outcomes) || !is.list(outcomes) || length(outcomes) == 0) {
    return(list())
  }
  keep <- vapply(outcomes, inherits, logical(1), "pmatools")
  outcomes[keep]
}

# One-row-per-outcome summary used by the saved-outcome list UI.
# `signature` is the signature of the dataset currently loaded; when given,
# the `stale` column marks outcomes saved from a different dataset.
pma_outcome_summary_df <- function(outcomes, signature = NULL) {
  outcomes <- pma_outcomes_list(outcomes)
  if (length(outcomes) == 0) {
    return(data.frame(name = character(0), k = character(0),
                      effect = character(0), certainty = character(0),
                      stale = logical(0),
                      stringsAsFactors = FALSE))
  }
  data.frame(
    name = names(outcomes),
    k = vapply(outcomes, function(g) {
      k <- g$meta$k %||% NA_integer_
      if (is.na(k)) "-" else as.character(k)
    }, character(1)),
    effect = vapply(outcomes, function(g) {
      # format_effect() is pmatools public API as of 0.5.0 (the dot-prefixed
      # .format_effect() is only a back-compat alias) -- keep the public name.
      out <- tryCatch(format_effect(g$meta, g$outcome_type), error = function(e) NA_character_)
      if (is.null(out) || is.na(out)) "-" else gsub("\n", "; ", out)
    }, character(1)),
    certainty = vapply(outcomes, function(g) g$certainty %||% "-", character(1)),
    stale = unname(pma_outcomes_stale(outcomes, signature)),
    stringsAsFactors = FALSE, row.names = NULL
  )
}

# Saved-outcome list with per-row Move up / Move down, Primary and Remove
# controls. Every button writes the outcome name to a single input id via
# Shiny.setInputValue rather than creating one observer per row, so rows can
# come and go freely. The move and primary payloads carry a nonce because two
# consecutive clicks on the same row would otherwise send an identical value
# and the observer would not fire the second time.
pma_saved_outcomes_ui <- function(outcomes, delete_input_id = "outcome_delete",
                                  empty_text = NULL, signature = NULL,
                                  move_input_id = "outcome_move",
                                  primary_input_id = "outcome_primary",
                                  primary = character(0)) {
  df <- pma_outcome_summary_df(outcomes, signature = signature)
  if (nrow(df) == 0) {
    if (is.null(empty_text)) return(NULL)
    return(htmltools::p(class = "pma-card-subtitle", empty_text))
  }
  primary <- as.character(primary %||% character(0))
  .name_lit <- function(x) jsonlite::toJSON(x, auto_unbox = TRUE)
  .row_button <- function(input_id, name, extra = NULL, label, title,
                          disabled = FALSE) {
    payload <- c(list(name = name), extra, list(nonce = 0))
    js <- sprintf(
      "Shiny.setInputValue('%s', Object.assign(%s, {nonce: Math.random()}), {priority: 'event'})",
      input_id, jsonlite::toJSON(payload, auto_unbox = TRUE))
    htmltools::tags$button(
      type  = "button",
      class = "btn btn-secondary",
      title = title,
      disabled = if (isTRUE(disabled)) NA else NULL,
      style = paste("padding: 0.2rem 0.5rem; font-size: 0.8rem;",
                    if (isTRUE(disabled)) "opacity: 0.4;" else ""),
      onclick = if (isTRUE(disabled)) NULL else js,
      label)
  }
  rows <- lapply(seq_len(nrow(df)), function(i) {
    is_primary <- df$name[i] %in% primary
    htmltools::div(
      style = paste(
        "display: flex; align-items: center; gap: 0.75rem;",
        "padding: 0.5rem 0.25rem;",
        "border-top: 1px solid hsl(var(--border));"),
      # Row order is a statement about priority in a Summary of Findings
      # table, so it is under the reviewer's control rather than fixed to the
      # order the outcomes happened to be saved in.
      htmltools::div(
        style = "display: flex; flex-direction: column; gap: 0.15rem;",
        .row_button(move_input_id, df$name[i], list(dir = "up"),
                    label = htmltools::HTML("&#9650;"),
                    title = "Move up", disabled = i == 1L),
        .row_button(move_input_id, df$name[i], list(dir = "down"),
                    label = htmltools::HTML("&#9660;"),
                    title = "Move down", disabled = i == nrow(df))
      ),
      htmltools::div(
        style = "flex: 1 1 auto; min-width: 0;",
        htmltools::div(style = "font-weight: 600;", df$name[i]),
        htmltools::div(
          style = "font-size: 0.8rem; color: hsl(var(--muted-foreground));",
          sprintf("k = %s | %s", df$k[i], df$effect[i])),
        if (isTRUE(df$stale[i])) htmltools::div(
          style = sprintf("font-size: 0.78rem; margin-top: 0.15rem; color: %s;",
                          PMA_ALERT_FG),
          "Saved from a dataset other than the one currently loaded."
        ) else NULL
      ),
      if (isTRUE(df$stale[i])) htmltools::div(pma_stale_badge()) else NULL,
      htmltools::div(pma_certainty_badge(df$certainty[i])),
      htmltools::tags$button(
        type  = "button",
        class = if (is_primary) "btn btn-primary" else "btn btn-secondary",
        title = paste0("Outcomes marked primary are grouped under a ",
                       "\"Primary outcomes\" heading in the table."),
        style = "padding: 0.2rem 0.6rem; font-size: 0.8rem;",
        onclick = sprintf(
          "Shiny.setInputValue('%s', {name: %s, nonce: Math.random()}, {priority: 'event'})",
          primary_input_id, .name_lit(df$name[i])),
        if (is_primary) "Primary" else "Mark primary"),
      htmltools::tags$button(
        type  = "button",
        class = "btn btn-secondary",
        style = "padding: 0.2rem 0.6rem; font-size: 0.8rem;",
        onclick = sprintf(
          "Shiny.setInputValue('%s', %s, {priority: 'event'})",
          delete_input_id, .name_lit(df$name[i])),
        "Remove")
    )
  })
  htmltools::div(style = "margin-top: 0.5rem;", rows)
}

# "+ Add next outcome". Shown at the bottom of Step 4's combined Summary of
# Findings card and beside the Save button on Step 3's Final certainty tab, so
# the reviewer can start the next outcome straight from either place. Both
# copies write to the same input id via Shiny.setInputValue (rather than being
# two actionButtons sharing an id), because only one step body is ever mounted
# at a time and this keeps that assumption out of the code.
pma_add_next_outcome_button <- function(input_id = "add_next_outcome",
                                        style = NULL) {
  htmltools::tags$button(
    type  = "button",
    class = "btn btn-secondary",
    style = paste("margin-top: 0.5rem;", style),
    onclick = sprintf(
      "Shiny.setInputValue('%s', Math.random(), {priority: 'event'})",
      input_id),
    "+ Add next outcome")
}

# GRADE certainty badge
pma_certainty_badge <- function(label) {
  cls <- switch(tolower(label),
    "high"     = "grade-high",
    "moderate" = "grade-moderate",
    "low"      = "grade-low",
    "very low" = "grade-vlow",
    "grade-low"
  )
  symbol <- switch(label,
    "High"     = htmltools::HTML("&#8853;&#8853;&#8853;&#8853;"),
    "Moderate" = htmltools::HTML("&#8853;&#8853;&#8853;&#9675;"),
    "Low"      = htmltools::HTML("&#8853;&#8853;&#9675;&#9675;"),
    "Very Low" = htmltools::HTML("&#8853;&#9675;&#9675;&#9675;"),
    htmltools::HTML("")
  )
  htmltools::span(class = paste("pma-badge", cls),
                  htmltools::HTML(paste0(label, " ", as.character(symbol))))
}

# Downgrade chip - shows -0/-1/-2 next to judgment badge
pma_downgrade_chip <- function(judgment) {
  j  <- judgment %||% "no"
  # 3-level mapping (v0.3+); legacy "some"/"very_serious" still mapped.
  dg <- c(no = 0, some = -1, some_concerns = -1,
          serious = -2, very_serious = -2)[[j]]
  if (is.null(dg) || is.na(dg)) dg <- 0
  cls <- if (dg == 0) "grade-high"
         else if (dg == -1) "grade-low"
         else "grade-vlow"
  label <- if (dg == 0) "+0" else as.character(dg)
  htmltools::span(class = paste("pma-badge pma-chip", cls), label)
}

# Generic judgment badge
pma_judgment_badge <- function(judgment) {
  cls <- switch(judgment,
    "no"            = "grade-high",
    "some"          = "grade-low",
    "some_concerns" = "grade-low",
    "serious"       = "grade-vlow",
    "very_serious"  = "grade-vlow",
    "grade-low"
  )
  label <- switch(judgment,
    "no"            = "No concern",
    "some"          = "Some concerns",
    "some_concerns" = "Some concerns",
    "serious"       = "Serious",
    "very_serious"  = "Serious",
    judgment
  )
  htmltools::span(class = paste("pma-badge", cls), label)
}

# Render a base R plot to a temp PNG and trim white margins via {magick}.
# Returns a list compatible with shiny::renderImage().
pma_render_trimmed <- function(plot_fn,
                               width    = 1400,
                               height   = 2400,
                               res      = 130,
                               fuzz     = 3,
                               bg       = "white") {
  png_path <- tempfile(fileext = ".png")
  grDevices::png(png_path, width = width, height = height,
                 res = res, bg = bg)
  ok <- tryCatch({ plot_fn(); TRUE },
                 error = function(e) FALSE)
  grDevices::dev.off()

  if (!isTRUE(ok)) {
    return(list(src = png_path, contentType = "image/png",
                width = "100%"))
  }

  if (requireNamespace("magick", quietly = TRUE)) {
    img <- tryCatch({
      i <- magick::image_read(png_path)
      i <- magick::image_trim(i, fuzz = fuzz)
      i <- magick::image_border(i, color = bg, geometry = "30x30")
      magick::image_write(i, png_path)
      TRUE
    }, error = function(e) FALSE)
  }

  list(src = png_path, contentType = "image/png", width = "100%")
}

# Funnel plot display panel — sizing controls for the renderImage canvas
# plus optional xlim and Egger-annotation toggle. Shared between Step2
# (Meta-analysis tab) and Step3 (Publication bias tab). `include_egger =
# FALSE` for the trim-and-fill funnel where Egger does not apply.
pma_funnel_display_panel <- function(prefix, include_egger = TRUE) {
  htmltools::tags$details(
    style = "margin-top: 0.5rem;",
    htmltools::tags$summary("Funnel plot display"),
    htmltools::div(
      class = "pma-display-grid",
      shiny::numericInput(paste0(prefix, "_funnel_width"),
                          "Width (px)",  value = 1400,
                          min = 400, step = 100, width = "100%"),
      shiny::numericInput(paste0(prefix, "_funnel_height"),
                          "Height (px)", value = 1400,
                          min = 400, step = 100, width = "100%"),
      shiny::numericInput(paste0(prefix, "_funnel_xlim_lo"),
                          "x-min", value = NA, width = "100%"),
      shiny::numericInput(paste0(prefix, "_funnel_xlim_hi"),
                          "x-max", value = NA, width = "100%"),
      if (isTRUE(include_egger)) htmltools::div(
        class = "pma-span-4",
        shiny::checkboxInput(paste0(prefix, "_funnel_show_egger"),
                             "Show Egger annotation", TRUE)
      ) else NULL
    )
  )
}

# Server-side helper to collect funnel display inputs into a list.
pma_funnel_display_args <- function(input, prefix, include_egger = TRUE) {
  lo <- input[[paste0(prefix, "_funnel_xlim_lo")]]
  hi <- input[[paste0(prefix, "_funnel_xlim_hi")]]
  xlim <- if (!is.null(lo) && !is.null(hi) &&
              !is.na(lo) && !is.na(hi) && lo < hi) c(lo, hi) else NULL
  w  <- input[[paste0(prefix, "_funnel_width")]]
  h  <- input[[paste0(prefix, "_funnel_height")]]
  list(
    width      = if (is.numeric(w) && !is.na(w) && w > 0) as.integer(w) else 1400L,
    height     = if (is.numeric(h) && !is.na(h) && h > 0) as.integer(h) else 1400L,
    xlim       = xlim,
    show_egger = if (isTRUE(include_egger))
                   isTRUE(input[[paste0(prefix, "_funnel_show_egger")]])
                 else NA
  )
}

# ---------------------------------------------------------------------------
# Forest plot display: smart defaults
#
# Every forest panel in the app (Step 2 and the four Step 3 domain tabs) has
# the same five text fields plus two "blank rows" numerics. The helpers below
# (a) name those input ids in one place, (b) derive what the app WOULD fill in
# from the outcome definition, and (c) prefill them without ever clobbering a
# value the user typed.
# ---------------------------------------------------------------------------

# Input ids of the five prefillable text fields of a forest display panel.
# `prefix = NULL` (or "") means the Step 2 panel, whose ids carry no prefix.
pma_forest_label_ids <- function(prefix = NULL) {
  p <- prefix %||% ""
  if (length(p) != 1 || is.na(p) || !nzchar(p)) {
    return(c(title        = "forest_title",
             label_e      = "label_e",
             label_c      = "label_c",
             favors_left  = "favors_left",
             favors_right = "favors_right"))
  }
  c(title        = paste0(p, "_title"),
    label_e      = paste0(p, "_label_e"),
    label_c      = paste0(p, "_label_c"),
    favors_left  = paste0(p, "_favors_left"),
    favors_right = paste0(p, "_favors_right"))
}

# Input ids of the two "blank rows around the pooled result" numerics.
# Step 2 and Step 3 disagree on the suffix, so never build these by hand.
pma_forest_addrow_ids <- function(prefix = NULL) {
  p <- prefix %||% ""
  if (length(p) != 1 || is.na(p) || !nzchar(p)) {
    return(c(above = "addrows_above_overall",
             below = "addrows_below_overall"))
  }
  c(above = paste0(p, "_addrows_above"),
    below = paste0(p, "_addrows_below"))
}

# The whole "Forest plot display" <details>, in one place.
#
# Step 2 and each of the four Step 3 domain tabs used to carry a hand-copied
# version of this panel; the two copies had already drifted apart in their id
# scheme (Step 2's `addrows_above_overall` against Step 3's
# `<prefix>_addrows_above`), which is exactly what pma_forest_addrow_ids()
# exists to absorb. Ids are therefore never built by hand here either: the five
# text fields come from pma_forest_label_ids() and the two blank-row numerics
# from pma_forest_addrow_ids(). Only x-min / x-max and the per-arm column
# toggle follow the plain `<prefix>_<name>` rule in both steps, so those three
# are derived locally.
#
# `prefix = NULL` (or "") builds the Step 2 panel, whose ids carry no prefix.
pma_forest_display_panel <- function(prefix = NULL) {
  labels  <- pma_forest_label_ids(prefix)
  addrows <- pma_forest_addrow_ids(prefix)
  p <- prefix %||% ""
  bare <- length(p) != 1 || is.na(p) || !nzchar(p)
  .id <- function(name) if (bare) name else paste0(p, "_", name)

  htmltools::tags$details(
    style = "margin-top: 0.5rem;",
    htmltools::tags$summary("Forest plot display"),
    htmltools::div(
      class = "pma-display-grid",
      htmltools::div(
        class = "pma-span-4",
        shiny::textInput(labels[["title"]], "Title", value = "", width = "100%")),

      shiny::textInput(labels[["label_e"]], "Intervention label", value = "", width = "100%"),
      shiny::textInput(labels[["label_c"]], "Control label",      value = "", width = "100%"),
      shiny::textInput(labels[["favors_left"]],  "Favors (left)",  placeholder = "e.g., Favors Control", width = "100%"),
      shiny::textInput(labels[["favors_right"]], "Favors (right)", placeholder = "e.g., Favors CBT-I",   width = "100%"),

      shiny::numericInput(.id("xlim_lo"), "x-min", value = NA, width = "100%"),
      shiny::numericInput(.id("xlim_hi"), "x-max", value = NA, width = "100%"),

      # Blank rows around the pooled result. Always visible: they matter most
      # once the per-arm columns are hidden (that is when the heterogeneity
      # footer can collide with the x-axis) but they are legitimate spacing
      # controls at any time, and the conditionalPanels that used to hide them
      # only toggled display anyway.
      #
      # Defaults are NOT symmetric, and deliberately so:
      #  * above = 1 reproduces the blank row meta::forest() draws by default
      #    (pma_addrow_above() has always treated blank as 1). Rendered with 0
      #    the pooled "Random effects model" row butts straight up against the
      #    last study row.
      #  * below is left blank = automatic, because plot_forest()'s
      #    .auto_addrow_below() is what keeps the heterogeneity line clear of
      #    the x-axis band and the Favors labels; typing 0 switches that
      #    heuristic off.
      htmltools::p(class = "pma-card-subtitle pma-span-4",
        paste0("Blank rows around the pooled result. If the ",
               "heterogeneity text overlaps the x-axis - most ",
               "likely once the per-arm columns are hidden - use ",
               "these to move it up or down. Above: 0 removes the ",
               "blank row before the pooled result. Below: blank ",
               "= automatic.")),
      shiny::numericInput(addrows[["above"]], "Blank rows above pooled result",
                          value = 1, min = 0, step = 1, width = "100%"),
      shiny::numericInput(addrows[["below"]], "Blank rows below pooled result",
                          value = NA, min = 0, step = 1, width = "100%"),

      # One checkbox, not two: plot_forest() keeps show_n and show_events as
      # separate arguments (correct for a library), but there is no case where
      # a user wants the N columns without the per-arm data columns, so the UI
      # drives both from a single value.
      htmltools::div(class = "pma-span-4",
        shiny::checkboxInput(.id("show_arm_columns"),
          "Show per-arm data columns (events or mean & SD, and N)",
          TRUE))
    )
  )
}

# Derive the "Favors ..." axis labels from the outcome direction.
#
# `small_values` is the pmatools vocabulary set in Step 2:
#   "undesirable" - a smaller value is worse (response, remission), so a
#                   larger effect favours the intervention: right = intervention.
#   "desirable"   - a smaller value is better (mortality, symptom score), so
#                   the sides are mirrored.
# Anything else (not yet chosen, unrecognised) or a missing arm name yields
# empty strings: better no prefill than a wrong direction on the axis.
pma_favors_labels <- function(small_values, intervention, control) {
  .clean <- function(x) {
    if (is.null(x) || length(x) != 1 || is.na(x)) return("")
    trimws(as.character(x))
  }
  sv <- .clean(small_values)
  iv <- .clean(intervention)
  ct <- .clean(control)
  none <- list(left = "", right = "")
  if (!nzchar(iv) || !nzchar(ct)) return(none)
  if (identical(sv, "undesirable")) {
    list(left = paste("Favors", ct), right = paste("Favors", iv))
  } else if (identical(sv, "desirable")) {
    list(left = paste("Favors", iv), right = paste("Favors", ct))
  } else {
    none
  }
}

# Coerce the "blank rows below the pooled result" input. Blank / NA / invalid
# means "let plot_forest() decide" (its .auto_addrow_below() heuristic), which
# is expressed as NULL.
pma_addrow_below <- function(x) {
  if (is.null(x) || length(x) != 1) return(NULL)
  x <- suppressWarnings(as.numeric(x))
  if (is.na(x) || !is.finite(x) || x < 0) return(NULL)
  x
}

# Same for "blank rows above the pooled result", where there is no auto mode;
# a blank field falls back to the historical default of one row.
pma_addrow_above <- function(x, default = 1) {
  if (is.null(x) || length(x) != 1) return(default)
  x <- suppressWarnings(as.numeric(x))
  if (is.na(x) || !is.finite(x) || x < 0) return(default)
  x
}

# Prefill a textInput without ever overwriting something the user typed.
#
# Design notes (this generalises the former Step 3 `.auto_name` observer):
#  * `shiny::observe()`, not `observeEvent()`: the field must also be filled
#    the first time the input appears, i.e. when the step body is rendered.
#  * `mem` is a plain environment, NOT a reactiveVal: it records the last value
#    this observer wrote, and a reactiveVal would make our own write re-trigger
#    the observer.
#  * The field is only updated when its current value is one we could have put
#    there ourselves - empty, an explicitly whitelisted `extra_auto` value, or
#    our own previous write. Anything else is the user's text and is left alone.
pma_autofill_text <- function(input, session, input_id, expected_fn,
                              extra_auto = character(0)) {
  mem <- new.env(parent = emptyenv())
  mem$last <- NULL
  shiny::observe({
    cur <- input[[input_id]]
    if (is.null(cur)) return()
    expected <- tryCatch(expected_fn(), error = function(e) NULL)
    if (is.null(expected) || length(expected) != 1 || is.na(expected)) return()
    expected <- as.character(expected)
    auto_filled <- unique(c("", extra_auto, mem$last))
    if (cur %in% auto_filled && !identical(cur, expected)) {
      mem$last <- expected
      shiny::updateTextInput(session, input_id, value = expected)
    }
  })
  invisible(NULL)
}

# Wire all five prefillable text fields of one forest display panel.
#
# `values_fn` is a reactive (or plain function) returning a list with the names
# title / label_e / label_c / favors_left / favors_right. `title_suffix` is
# appended to a non-empty title only, so panels that plot a stratified version
# of the outcome carry the same title the export bundle writes.
pma_autofill_forest_panel <- function(input, session, prefix = NULL,
                                      values_fn, title_suffix = "") {
  ids <- pma_forest_label_ids(prefix)
  for (key in names(ids)) {
    # local() is required: without it every closure below would capture the
    # same loop variable and all five observers would end up watching the last
    # key only.
    local({
      k  <- key
      id <- ids[[k]]
      sfx <- if (identical(k, "title")) title_suffix else ""
      pma_autofill_text(
        input, session, id,
        expected_fn = function() {
          vals <- values_fn()
          v <- vals[[k]] %||% ""
          if (length(v) != 1 || is.na(v)) v <- ""
          v <- as.character(v)
          if (nzchar(v) && nzchar(sfx)) paste0(v, sfx) else v
        }
      )
    })
  }
  invisible(NULL)
}

# Banner (used for the Indirectness review reminder and the risk-of-bias
# analysis-set notice). Takes any number of children so callers can pass a
# single string (the original signature) or structured tags.
pma_banner <- function(...) {
  htmltools::div(class = "pma-banner", ...)
}

# --------------------------------------------------------------------------
# Risk-of-bias analysis set (Core GRADE 4 Fig 2)
# --------------------------------------------------------------------------
# pmatools 0.5 refits the meta-analysis on the low risk-of-bias subset when
# the flowchart reaches "use low risk of bias studies only" (rob_refit =
# TRUE, the default). Every domain, the rating target, the baseline risk and
# the Summary of Findings then rest on that restricted estimate, so the
# pooled effect shown in Step 3 can differ from the one computed in Step 2.
# The package reports this through an R-level message() that never reaches
# the browser; the helpers below put the same facts on screen.
#
# Returns NULL whenever the analysis rests on all studies, so every caller
# can render nothing at all rather than an empty container.
pma_analysis_set_info <- function(g) {
  if (is.null(g)) return(NULL)
  if (!identical(g$rob_analysis_set %||% "all", "low_only")) return(NULL)

  meta_full <- g$meta_full %||% g$meta
  meta_used <- g$meta
  if (is.null(meta_used) || is.null(meta_full)) return(NULL)

  # $rob_refit is FALSE when the restriction was recommended but skipped
  # (fewer than two low risk-of-bias studies, or update.meta() failed). The
  # recommendation still stands, but $meta is then the full analysis.
  refit <- isTRUE(g$rob_refit)

  studlab_full <- as.character(meta_full$studlab %||% character(0))
  studlab_used <- as.character(meta_used$studlab %||% character(0))
  dropped <- if (refit) setdiff(studlab_full, studlab_used) else character(0)

  .k <- function(m, lab) {
    k <- suppressWarnings(as.integer(m$k %||% NA_integer_))
    if (is.na(k)) length(lab) else k
  }
  .eff <- function(m) {
    out <- tryCatch(format_effect(m, g$outcome_type, prediction = FALSE),
                    error = function(e) NA_character_)
    if (is.null(out) || length(out) != 1 || is.na(out)) "not estimable"
    else gsub("\n", "; ", out)
  }

  list(
    refit      = refit,
    k_full     = .k(meta_full, studlab_full),
    k_used     = .k(meta_used, studlab_used),
    dropped    = dropped,
    effect_all = .eff(meta_full),
    effect_low = if (refit) .eff(meta_used) else NULL
  )
}

# One-line state notice for the persistent Step 3 indicator. Self-contained:
# it reads the rated object only, so it is unaffected by anything the sticky
# certainty badge / summary do.
pma_analysis_set_indicator <- function(g) {
  info <- pma_analysis_set_info(g)
  if (is.null(info)) return(NULL)
  htmltools::div(
    class = "pma-analysis-set",
    htmltools::span(class = "pma-analysis-set-label", "Analysis set"),
    if (info$refit) {
      sprintf("low risk-of-bias studies only (%d of %d studies)",
              info$k_used, info$k_full)
    } else {
      sprintf(paste0("all %d studies; the recommended low risk-of-bias ",
                     "restriction could not be applied"), info$k_full)
    }
  )
}

# Full explanatory banner for the Risk of Bias and Final certainty tabs.
# Excluded study labels are folded into a <details> once the list grows past
# eight, so a large meta-analysis cannot push the rest of the tab off screen.
pma_analysis_set_banner <- function(g) {
  info <- pma_analysis_set_info(g)
  if (is.null(info)) return(NULL)

  rule <- paste0(
    "Core GRADE 4 Fig 2 recommends restricting the analysis to low ",
    "risk-of-bias studies when they and the high risk-of-bias studies give ",
    "substantially different estimates.")

  if (!info$refit) {
    return(pma_banner(
      htmltools::strong("Restriction recommended but not applied. "),
      rule,
      sprintf(paste0(" Here the restriction could not be carried out (fewer ",
                     "than two low risk-of-bias studies remained, or the ",
                     "refit failed), so every number shown in Step 3 is ",
                     "still the all-studies analysis of %d studies: %s."),
              info$k_full, info$effect_all)
    ))
  }

  estimate_row <- function(label, value) {
    htmltools::div(
      class = "pma-analysis-set-estimate",
      htmltools::span(class = "pma-analysis-set-estimate-label", label),
      htmltools::span(class = "pma-analysis-set-estimate-value", value)
    )
  }
  dropped_list <- htmltools::span(
    class = "pma-analysis-set-studies",
    paste(info$dropped, collapse = ", "))

  pma_banner(
    htmltools::strong("Analysis restricted to low risk-of-bias studies. "),
    rule,
    sprintf(paste0(" Every domain judgment, the rating target, the baseline ",
                   "risk and the Summary of Findings below therefore rest on ",
                   "%d of %d studies, not on the pooled estimate reported in ",
                   "Step 2."), info$k_used, info$k_full),
    htmltools::div(
      class = "pma-analysis-set-compare",
      estimate_row(sprintf("All studies (%d)", info$k_full), info$effect_all),
      estimate_row(sprintf("Low risk of bias only (%d)", info$k_used),
                   info$effect_low)
    ),
    if (length(info$dropped)) {
      htmltools::div(
        class = "pma-analysis-set-dropped",
        sprintf("%d %s excluded from the estimate above: ",
                length(info$dropped),
                if (length(info$dropped) == 1) "study" else "studies"),
        if (length(info$dropped) > 8) {
          htmltools::tags$details(
            class = "pma-analysis-set-details",
            htmltools::tags$summary("Show the excluded study labels"),
            dropped_list)
        } else {
          dropped_list
        }
      )
    }
  )
}

# Reference line with optional DOI link.
# Call as pma_reference(text, doi) or pma_reference(text) for plain text.
pma_reference <- function(text, doi = NULL) {
  ref_content <- if (!is.null(doi) && nzchar(doi)) {
    htmltools::tags$a(
      href = paste0("https://doi.org/", doi),
      target = "_blank",
      text
    )
  } else text
  htmltools::p(class = "pma-reference",
    style = "font-style: italic; color: hsl(var(--muted-foreground)); font-size: 0.85rem;",
    "Reference: ", ref_content
  )
}

# Collapsible "How is this judged?" block — clickable to expand long
# educational copy.
pma_how_collapse <- function(body) {
  htmltools::tags$details(
    class = "pma-how-details",
    htmltools::tags$summary("How is this judged? (click to expand)"),
    htmltools::div(
      class = "pma-how-body",
      style = "margin-top: 0.6rem; line-height: 1.55; font-size: 0.9rem;",
      htmltools::p(body)
    )
  )
}

# Wizard navigation buttons (Back / Next).
# Use HTML entities to dodge Latin-1 encoding issues on shinyapps.io build.
pma_wizard_nav <- function(current_step, max_step = 4,
                           back_id = "btn_back", next_id = "btn_next",
                           next_label = NULL,
                           next_disabled = FALSE) {
  arrow_left  <- htmltools::HTML("&#8592;")  # left arrow
  arrow_right <- htmltools::HTML("&#8594;")  # right arrow
  next_label  <- next_label %||% htmltools::tagList("Next ", arrow_right)
  back_label  <- htmltools::tagList(arrow_left, " Back")
  htmltools::div(
    style = "display: flex; justify-content: space-between; margin-top: 1.5rem;",
    if (current_step > 1) {
      shiny::actionButton(back_id, back_label, class = "btn btn-secondary")
    } else htmltools::div(),
    if (current_step < max_step) {
      # TRUE, not the string "disabled": shiny >= 1.9 gives actionButton() a
      # real `disabled` formal it tests with isTRUE(), so a string silently
      # produced an enabled button. NULL (not FALSE) when enabled, so the
      # attribute is dropped rather than rendered as disabled="FALSE" should
      # the argument ever land in `...` on an older shiny.
      shiny::actionButton(next_id, next_label,
                          class = "btn btn-primary",
                          disabled = if (isTRUE(next_disabled)) TRUE else NULL)
    } else htmltools::div()
  )
}

# ==========================================================================
# Summary of Findings presentation (Core GRADE 6)
# ==========================================================================
#
# Core GRADE 6 (Guyatt G, Yao L, Murad MH, et al. BMJ 2025;389:e083866)
# presents an eight-column summary of findings table. pmatools 0.5 ships that
# layout as style = "bmj"; the package default, "gradepro", is a six-column
# layout that omits follow-up, study design, the difference between arms, the
# rate-down reason and the plain language summary.
#
# The app renders the Core GRADE 6 layout everywhere and does NOT offer the
# GRADEpro layout as an alternative. Two reasons:
#   1. Every other output in the wizard is written against the Core GRADE
#      series, so a second layout would be a second, unsourced standard.
#   2. The on-screen table, the exported sof_table.docx and the combined
#      table are all built from this one constant, so they cannot disagree.
# The Evidence Profile is a different table (nine columns, Core GRADE's
# evidence-profile format) and is unaffected.
PMA_SOF_STYLE   <- "bmj"
PMA_SOF_PALETTE <- "pastel"

# Percentage with enough resolution to distinguish the two rare-event bands.
pma_fmt_pct <- function(p, digits = 2) {
  if (is.null(p) || length(p) != 1L || !is.finite(p)) return("not estimable")
  paste0(formatC(100 * p, format = "f", digits = digits), "%")
}

# Free-text follow-up as it is printed under the outcome name. Core GRADE 6
# writes the cell as "Follow-up: ...", so the prefix is supplied here when the
# user did not type one.
pma_sof_follow_up <- function(x) {
  if (is.null(x) || length(x) != 1L || is.na(x)) return(NULL)
  x <- trimws(as.character(x))
  if (!nzchar(x)) return(NULL)
  if (grepl("^follow[ -]?up", x, ignore.case = TRUE)) x else paste0("Follow-up: ", x)
}

# Unit for the Difference column of a continuous outcome.
#
# The unit the reviewer typed describes the measurement scale, so it is the
# right label for a mean difference. A standardized mean difference is not on
# that scale, so its difference is labelled in standard deviation units
# whatever the reviewer typed; a ratio measure has no unit at all (the
# difference is printed "per 1000") and gets NULL.
pma_sof_unit <- function(g, unit = NULL) {
  sm <- as.character((g$meta$sm %||% "")[1])
  if (identical(sm, "SMD")) return("standard deviation units")
  if (!identical(sm, "MD")) return(NULL)
  if (is.null(unit) || length(unit) != 1L || is.na(unit)) return(NULL)
  unit <- trimws(as.character(unit))
  if (nzchar(unit)) unit else NULL
}

# Crude arm-level and pooled event rates, straight off the metabin arms.
# Returns NULL for anything that is not a binary meta-analysis.
pma_sof_event_rates <- function(meta_obj) {
  if (is.null(meta_obj)) return(NULL)
  ee <- meta_obj$event.e; ne <- meta_obj$n.e
  ec <- meta_obj$event.c; nc <- meta_obj$n.c
  if (is.null(ee) || is.null(ne) || is.null(ec) || is.null(nc)) return(NULL)
  if (length(ee) != length(ne) || length(ec) != length(nc)) return(NULL)
  keep_e <- is.finite(ee) & is.finite(ne) & ne > 0
  keep_c <- is.finite(ec) & is.finite(nc) & nc > 0
  if (!any(keep_e) && !any(keep_c)) return(NULL)
  ev_e <- sum(ee[keep_e]); n_e <- sum(ne[keep_e])
  ev_c <- sum(ec[keep_c]); n_c <- sum(nc[keep_c])
  n_tot <- n_e + n_c
  if (!is.finite(n_tot) || n_tot <= 0) return(NULL)
  list(
    intervention = if (n_e > 0) ev_e / n_e else NA_real_,
    control      = if (n_c > 0) ev_c / n_c else NA_real_,
    overall      = (ev_e + ev_c) / n_tot,
    events       = ev_e + ev_c,
    n            = n_tot
  )
}

# Core GRADE 6's rare-event trap.
#
# The Difference column and the "With intervention" column are both computed
# by applying the pooled relative effect to a baseline risk. Core GRADE 6
# warns that this misleads when the outcome is rare, naming two bands --
# "event rates <2% and most problematic <1%" -- and recommends that review
# authors generally conduct meta-analyses of risk differences instead.
#
# `g`             a pmatools object.
# `baseline_risk` the risk the table is actually drawn against when it is not
#                 the object's own (the responder proportion of a Chinn
#                 dichotomisation).
#
# Returns NULL when nothing is rare, otherwise a list with the band, the
# computed rates, a one-line headline and the full note. The note is the same
# text on screen and in the exported docx.
PMA_RARE_BAND_1 <- 0.01
PMA_RARE_BAND_2 <- 0.02

pma_rare_event_alert <- function(g, baseline_risk = NULL, label = NULL) {
  if (is.null(g)) return(NULL)
  rates <- pma_sof_event_rates(g$meta)
  br    <- baseline_risk
  if (is.null(br)) br <- g$baseline_risk
  if (!is.numeric(br) || length(br) != 1L || !is.finite(br)) br <- NA_real_

  # Every rate the absolute-effect columns rest on: the two observed arm
  # rates, the pooled rate, and the baseline risk the table is drawn against
  # (which the reviewer may have set by hand).
  cand <- c(rates$overall, rates$control, rates$intervention, br)
  cand <- cand[is.finite(cand) & cand > 0]
  if (length(cand) == 0) return(NULL)
  lowest <- min(cand)
  if (lowest >= PMA_RARE_BAND_2) return(NULL)

  band <- if (lowest < PMA_RARE_BAND_1) "below 1%" else "below 2%"

  observed <- if (is.null(rates)) {
    ""
  } else {
    sprintf(paste0(
      "Observed event rates: %s overall (%s of %s participants), %s in the ",
      "control arm, %s in the intervention arm. "),
      pma_fmt_pct(rates$overall),
      format(rates$events, big.mark = ",", scientific = FALSE, trim = TRUE),
      format(rates$n,      big.mark = ",", scientific = FALSE, trim = TRUE),
      pma_fmt_pct(rates$control), pma_fmt_pct(rates$intervention))
  }
  baseline_txt <- if (is.finite(br)) {
    sprintf("Baseline risk used for the absolute columns: %s. ", pma_fmt_pct(br))
  } else ""

  headline <- sprintf("Rare outcome%s - lowest event rate %s (%s).",
                      if (is.null(label)) "" else paste0(" (", label, ")"),
                      pma_fmt_pct(lowest), band)

  detail <- paste0(
    observed, baseline_txt,
    "Core GRADE 6 warns that applying a relative effect to a baseline risk is ",
    "misleading for rare outcomes, at \"event rates <2% and most problematic ",
    "<1%\", and recommends that review authors generally conduct ",
    "meta-analyses of risk differences instead ",
    "(Guyatt et al. BMJ 2025;389:e083866). ",
    "The Difference column and the \"With intervention\" column are still ",
    "computed from the baseline risk and the pooled relative effect, and are ",
    "shown unchanged; read them with that warning in mind, and consider ",
    "reporting the risk difference from Step 2's rare-events workflow instead."
  )
  note <- paste0("Rare-event caution (Core GRADE 6). ", headline, " ", detail)

  list(band = band, lowest = lowest, rates = rates, baseline_risk = br,
       headline = headline, detail = detail, note = note, label = label)
}

# Amber banner for a rare-event alert. NULL-safe so callers can drop the
# result straight into a tagList.
pma_rare_event_banner <- function(alert) {
  if (is.null(alert)) return(NULL)
  htmltools::div(
    style = paste0(
      "padding: 0.75rem 1rem; margin-bottom: 1rem; ",
      "background: ", PMA_ALERT_BG, "; border-left: 4px solid ", PMA_ALERT_FG,
      "; border-radius: 4px; font-size: 0.9rem;"),
    htmltools::strong(paste0("Rare events. ", alert$headline, " ")),
    alert$detail
  )
}

# One Core GRADE 6 feature neither pmatools layout implements, plus what is
# left of two others: pmatools now fills the arm-level columns of a continuous
# outcome from the control arms (but only when the analysis carries them), and
# now footnotes the numbers behind a downgrade (but only for the three domains
# that record them). Stated in the table footer and again under the table, so
# a reader cannot take the table for a complete Core GRADE 6 summary of
# findings.
PMA_SOF_LIMITATIONS_NOTE <- paste0(
  "Not implemented in this table (Core GRADE 6 features pmatools does not yet ",
  "produce). \"Not reported\" rows: outcomes the evidence base did not ",
  "measure are absent from this table, so it is not the full list of outcomes ",
  "important to patients. Arm-level values for continuous outcomes -- the ",
  "control-group value, the intervention-group value and the difference, ",
  "which Core GRADE 6 calls its preferred approach -- are now reported, ",
  "except where the analysis carries no arm-level means (a generic ",
  "inverse-variance analysis) or uses a ratio-of-means measure; those still ",
  "leave the two arm columns empty. Per-domain footnotes now state what drove ",
  "each downgrade for risk of bias, inconsistency and imprecision; a rated ",
  "down indirectness or publication bias domain is still only named in the ",
  "certainty cell, with its reasoning left in the Evidence Profile and in ",
  "that domain's notes."
)

pma_sof_limitations_ui <- function() {
  htmltools::div(
    style = paste0(
      "margin-top: 0.75rem; padding: 0.6rem 0.85rem; border-radius: 4px; ",
      "border: 1px solid hsl(var(--border)); ",
      "font-size: 0.82rem; color: hsl(var(--muted-foreground));"),
    htmltools::strong("Not implemented in this table. "),
    "Core GRADE 6 also asks for \"Not reported\" rows for outcomes the ",
    "evidence base did not measure. Arm-level values for continuous outcomes ",
    "are now reported, except where the analysis carries no arm-level means ",
    "or uses a ratio-of-means measure. Per-domain footnotes now state what ",
    "drove each downgrade for risk of bias, inconsistency and imprecision; a ",
    "rated down indirectness or publication bias domain is still only named ",
    "in the certainty cell, with its reasoning left in the Evidence Profile. ",
    "The same statement is printed in the table footer, so it travels with ",
    "the exported document."
  )
}

# Append free-text footer lines to a Summary of Findings flextable, keeping
# the footer styling the vendored builders apply. Used for the rare-event
# caution and the limitations statement, so both reach the exported .docx.
pma_sof_add_notes <- function(ft, notes) {
  if (is.null(ft)) return(ft)
  notes <- notes[!vapply(notes, function(z) is.null(z) || is.na(z) ||
                           !nzchar(z), logical(1))]
  if (length(notes) == 0) return(ft)
  for (nt in notes) {
    ft <- flextable::add_footer_lines(ft, values = as.character(nt))
  }
  ft <- flextable::fontsize(ft, size = 8, part = "footer")
  ft <- flextable::color(ft, color = "#555555", part = "footer")
  ft
}

# The Core GRADE 6 layout is wider than the GRADEpro one (eight fixed-width
# columns totalling ~10.3 in against ~8.3 in), so every on-screen SoF table is
# wrapped in a horizontal scroller rather than being allowed to stretch the
# card. Colours, fonts and the dark header are unchanged.
pma_sof_scroller <- function(...) {
  htmltools::div(style = "overflow-x: auto; margin-top: 0.5rem;", ...)
}
